object Versions {
    const val build_gradle = "4.1.3"
    const val kotlin_version = "1.3.72"
    const val dagger_version = "2.36"
    const val coroutines_version = "1.3.0"
    const val retrofit_version = "2.9.0"
    const val timber_version = "4.7.1"
    const val nav_version = "2.3.5"
    const val androidx_core = "1.5.0"
    const val androidx_app_compat = "1.3.0"
    const val android_material = "1.3.0"
    const val constraint_layout = "2.0.4"
    const val android_legacy = "1.0.0"
    const val room_version = "2.3.0"
    const val rx_android = "3.0.0"
    const val glide_version = "4.12.0"
    const val carousel_view_version = "0.1.5"
    const val google_services = "4.3.5"
    const val firebase_platform = "27.1.0"
    const val firebase_crashlytics_gradle = "2.5.2"
}

object TestVersions {
    const val jUnit = "4.+"
    const val junit_ext = "1.1.2"
    const val espresso = "3.3.0"
    const val espresso_contrib = "3.1.0"
    const val mockito = "3.11.0"
    const val nhaarman_mockito = "2.2.0"
    const val androidx_arch_testing = "2.1.0"
    const val coroutines_testing = "1.5.0"
    const val mockito_inline = "2.13.0"
    const val android_implementation_test_rules = "1.1.0"
}